/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as messageDemoSol from "./MessageDemo.sol";
export type { messageDemoSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { Message } from "./MessageDemo.sol/Message";
export { Message__factory } from "./factories/MessageDemo.sol/Message__factory";
